import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import path from 'node:path';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// dev 构建直接输出到本地 dev vault 的插件目录（可用 GALAXY_OUTDIR 覆盖）；
// prod 输出到 ./dist 作为 release 资产。
const outDir = prod
	? path.resolve('./dist')
	: (process.env.GALAXY_OUTDIR ??
		path.resolve('./dev-vault/.obsidian/plugins/galaxy-view'));

fs.mkdirSync(outDir, { recursive: true });

const copyAssets = {
	name: 'copy-assets',
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) return;
			fs.copyFileSync('manifest.json', path.join(outDir, 'manifest.json'));
			fs.copyFileSync('styles.css', path.join(outDir, 'styles.css'));
			if (!prod) {
				// pjeby/hot-reload 监听该标记文件所在的插件目录
				fs.writeFileSync(path.join(outDir, '.hotreload'), '');
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outDir, 'main.js'),
	minify: prod,
	plugins: [copyAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
